### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by Spinicle** [justfoolingaround/animdl#1]
It would be helpfull if you let us know how to use it, not only that, when i tried to run the cli.py file, i got certain errors. Please try fixing these

**Comment by justfoolingaround** [comment]
Hey @Spinicle, the usage of the program is to simply run the provided `cli.py` file.

Please inform me about what the error you're getting from the file is (just run the `cli.py` file in a console/terminal).

If the error is along the lines of `ImportError: cannot import name 'Token' from 'prompt_toolkit.token'`, a simple workaround can be to downgrade the module by using `pip install prompt_toolkit==1.0.14`.

**Comment by justfoolingaround** [comment]
Also, this is what an successful use case may look like:
![image](https://user-images.githubusercontent.com/79979949/116981106-cefbdc00-ace6-11eb-80e8-649c3e966e1a.png)

**Comment by Spinicle** [comment]
Sorry for the late response but turns out I was busy, that aside, this is the error that I am getting.

![image](https://user-images.githubusercontent.com/70312979/117095398-e8069a80-ad83-11eb-930b-593d894ea1c8.png)

**Comment by justfoolingaround** [comment]
Oh oops, the issue seems to be with the installation of PyCrypto module. I assume it would've been there in every Python installation but I see I was wrong about it.

In any case, the easiest way of resolving this could be to install the module `pycryptodomex` using `pip install pycryptodomex`. I might as well update the requirements.txt as well. Thanks for reporting this issue!

**Comment by justfoolingaround** [comment]
As it seems, the issue has been removed. If the problem persists, we'll reopen this issue in the future.

**Comment by thaynos** [comment]
> pip install prompt_toolkit==1.0.14

i had this problem but even then it shows error 
![Uploading image.png…]()
