### ISSUE TITLE
Site request....

### ISSUE THREAD

**Issue by Itmedesu** [justfoolingaround/animdl#118]
Animesuge.to
https://animesuge.to/

**Comment by justfoolingaround** [comment]
That site is quite literally 9Anime which is already in the codebase.

**Comment by Itmedesu** [comment]
Can't open 9anime site 
![IMG_20220304_104929](https://user-images.githubusercontent.com/100840612/156704154-5eb2b85d-2fb4-4e50-b78f-cf19d2c2c609.jpg)

**Comment by Itmedesu** [comment]
Or can you say how to do it I will do it myself

**Comment by justfoolingaround** [comment]
It's `9anime` not `9Anime`.

**Comment by Itmedesu** [comment]
Not working...
can you say how to do it I will do it myself
![Screenshot_2022-03-04-12-09-51-77_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/100840612/156712838-c8d4dac2-7bf7-474b-a1d2-fdf0274f8f6d.png)

**Comment by justfoolingaround** [comment]
Man shut up about doing yourself.

The codebase is working just fine for me and your errors are not replicable. If you can't follow simple instructions given in the damn readme and have to be provided with solution that is in the readme in a GitHub issue, do realise that you are not capable of using the project.

What will you do yourself?

The codebase is incredibly complex and even the good Python developers working in top industries will be scratching their heads around the code.

While I do provide support to people who at least try and can work around at least some lines of the code, I can't provide development support to lost causes and complete beginners.

Your issue lies with the error message. Realise that it is an internet issue or an ISP issue. AnimeSuge is a mere 9Anime clone, the codebase has methods to override the default domain through configurations.

**I will not be adding AnimeSuge nor be giving *you* a development support.**

This project is not a mess-around project like the rest of the anime scrapers. This project has different values and foundations to it. Kindly, piss off with "I'll do it myself.".

**Comment by Itmedesu** [comment]
First of all sorry if I pissed you off
I was Just trying to ask a question men..
I know how hard it Is to make a python program
I am Also a Python Programmer Doing It for more than 8 years....(I also respect your Project)
And In The near future if someone asks a question just help them out.
It's Not good To get Angry...

**Comment by ArjixWasTaken** [comment]
Yeah it is a network error that has nothing to do with this project.
You cannot fix it by editing the codebase.

Using a vpn, or even switching from mobile data to wifi might fix it.

**Comment by brahmkshatriya** [comment]
@Itmedesu do this
![image](https://user-images.githubusercontent.com/69040506/156766354-5c81e1e2-276b-4d24-8f23-2009a4dd737a.png)
