### ISSUE TITLE
animixplay error

### ISSUE THREAD

**Issue by Avrozavr** [justfoolingaround/animdl#12]
hello, I have updated the animdl but this is what I got:

![изображение](https://user-images.githubusercontent.com/13178622/122905822-3a167600-d35a-11eb-9205-1a4191215efb.png)

**Comment by justfoolingaround** [comment]
Looks like there searching normally usually requires >4 characters. I have added a helper to this in the recent pushes, however, the update will probably not be pushed to the install package at the moment because this isn't a massive issue and >4 character requirement is quite standard in search engines. 

Try using `https://animixplay.to/v1/86` as your query to get it working.

**Comment by justfoolingaround** [comment]
Version bump `1.1.0` -> `1.2.0` fixes this completely. Give `animdl` a reinstall!
