### ISSUE TITLE
Log

### ISSUE THREAD

**Issue by Gojouisthebest** [justfoolingaround/animdl#124]
What is the the use of --log
Does it increases the downloading speed...
If Yes  how to use it...

**Comment by brahmkshatriya** [comment]
Where did you read that it increases speed?

**Comment by Gojouisthebest** [comment]
Don't know I  am just asking ...
Does it increases the speed

**Comment by brahmkshatriya** [comment]
No it isn't supposed to increase your speed

**Comment by Gojouisthebest** [comment]
Ok what's the  use of it...

**Comment by justfoolingaround** [comment]
Logging. Everything you see is an output set through logging. This has absolutely nothing to do with program performance and internet speed.

Could be please think before you make these issues, even a tiny bit?

If anything did increase your internet speed, I would happily set it as default instead of keeping it behind an argument.
