### ISSUE TITLE
Quality selection

### ISSUE THREAD

**Issue by haj1s** [justfoolingaround/animdl#15]
First of all, a great thing you got going on here, it's exactly what I was looking for :p.

second, I mainly use it to batch download animes and since quality affects the file size, it would be a lot more efficient for me to be able to lower the quality (and also because my display is 720p lol)

Keep up the good work!

**Comment by justfoolingaround** [comment]
Thank you!

Aight, so, all the sites added in this project have this, kind of, "source" quality, which is usually a singular quality MP4 from their servers. Exception to this is, AnimePahe, the only provider that supports a quality selection because it serves just HLS quality streams. To use this, just create a `animdl_config.json` file in the working directory for animdl, and then, just insert the following as the content of that file:
```json
{
    "preferred_quality": 1080
}
```
What this will do is select a quality in the HLS downloading, a MP4 download isn't possible to be downloaded at something that's not their real size 😔.

If you're looking for 720p streams, you can always use Anime1 or AnimeOut because they mainly contain 720p MP4 streams, all the others, except AnimePahe, contain the "standard" 1080p streams!

**Comment by haj1s** [comment]
alr, thank you and keep up the good work!
