### ISSUE TITLE
Anime providers (fallbacks for when majority of current break down or terminate permanently)

### ISSUE THREAD

**Issue by justfoolingaround** [justfoolingaround/animdl#151]
As the title states, this issue holds the anime providers that are going act as fallbacks when most of the projects current providers break beyond repair or go offline permanently.

Comments are welcome for adding a provider to this list.

**This is not in a hierarchical order.**

1. #119 [AnimeFLV](https://www.animeflv.net/)
2. #141  [AnimeWorld](https://aniworld.to/)

# Why not add all of these?

The codebase is already large enough. Unless an extension-style system is planned and implemented, adding more providers will affect project performance and maintainability. 

Moreover, the current providers are already heavily reliable; the project being, in some cases, the origin code for their scrapers.

**Comment by justfoolingaround** [comment]
Closed due to inactivity. Reopen when more insights are available.

**Comment by Makefile-dot-in** [comment]
Choosing the first two as fallback providers seems a bit silly: AniWave mostly provides German subs and dubs (with English subs for some newer anime, for which I assume at first no German subs were available), Bilibili is a Chinese video sharing site, and AnimeFLV seems to be for Spanish subs and dubs. If you're a monolingual English speaker, AnimeFLV probably isn't gonna replace a provider with English subs, and neither is AniWave a substitute for AniWorld if you're a German speaker who can't understand English well (or in my case, if you're trying to get better at German by rewatching anime in German), so they make for bad fallbacks.

As for BiliBili, its anime section seems to be a place where you can legally stream primarily Chinese anime – some of it free, some of it requiring a premium subscription. So I would say that it's not really interchangeable with the other providers that have Chinese anime since the overlap between pirates and users who are willing to pay for a subcription is probably pretty small.

So yeah, to conclude, these sources aren't really good fallbacks because they're not run-of-the-mill anime pirate sites with English subs like most of the existing providers. I think it would probably be best to make it so everything pertaining to a provider isn't mixed up outside the module for a given provider (currently at a quick glance it seems like provider code is spilled across just 2 more files in addition to the provider modules so this seems easy) and adding those sources. Or, failing that, perhaps removing some of the non-functioning providers. Or just not adding them and picking better fallback providers.

**Comment by barracuda156** [comment]
@justfoolingaround Any update on this? Default provider is dead.
