### ISSUE TITLE
too bleeding edge and no older version available

### ISSUE THREAD

**Issue by pirate486743186** [justfoolingaround/animdl#173]
I'm on debian, and you are using libraries that are too new for my system.

You have simply a master branch, no tags, no releases.... There's no easy way to use an older version. You should at least have some tags to segment the history so that we can download older versions. You could also consider not using libraries that are too new.

**Comment by justfoolingaround** [comment]
Which dependencies are too new?

It wouldn't matter if we had proper tagging or release system; this project is a scraper that deals with updating algorithms. Each update means that the previous version is done for.

The dependencies being used are not new at all. They should support all systems. Try to note the dependencies and show relevant errors.

**Comment by nate-moo** [comment]
Or just don't use a slow to update anything distro lmao

**Comment by ChazyTheBest** [comment]
@pirate486743186 

That's your own fault for using distros whose repositories have more than 80% outdated packages, and I'm talking more than 1-2 year old outdated (and I'm being generous with those estimates).

You may also have misconceptions, contrary to popular beliefs, arch and bleeding edge distros in general (such as fedora) are at the very least as stable as "stable" distros such as debian. I only had trouble (in the distant past) with distros that come with a full desktop installation by default (almost always it's because of an outdated config file with a hack or a name change w/e) or when I've been messing around with something new (trial and error). There's also the rare package name change, which breaks updates. But even then it's not like it can't be fixed in 1-5 minutes.

So again, your fault. The very nature of software is ever-changing, if you wanna go against that be prepared to suffer the consequences. You can't really expect a frozen/outdated piece of code to even work with something that's constantly being updated, like web applications.

**Comment by ArjixWasTaken** [comment]
just use a virtual env, thats why they exist
lol

**Comment by ArjixWasTaken** [comment]
@justfoolingaround i suppose you can make a workflow to package in AppImages, you can look at whine's repos, he does that a lot iirc

**Comment by ArjixWasTaken** [comment]
> btw i don't use arch

if you used arch this wouldn't even be a problem
in arch too old libraries are the issue, not too new
lmao

**Comment by ArjixWasTaken** [comment]
this issue is so old, that the libraries may have been updated for debian/ubuntu
