### ISSUE TITLE
[Feature Request]: Add the option to let URLs append to playlist to current running instance instead of starting new instance for every episode(mpv))

### ISSUE THREAD

**Issue by NaiveInvestigator** [justfoolingaround/animdl#192]
I really love using your project you've made! Once I've started using it I really couldn't turn back to the old ways. But I do have this one small pet peeve of mine tho. Every time I watch a episode I need to close mpv to watch the next episode, which I find it a bit frustrating at times and also doesn't seems efficient to open and close the player every time imho.

**Describe the solution you'd like**

I'd want animdl to pass the urls using the [`loadfile append-play`](https://mpv.io/manual/master/#command-interface-[%3Coptions%3E]]) command mpv has instead of opening new instances.

**Describe alternatives you've considered**
Or another way to do this also would be scrape all the urls at once and then save it to a .m3u file, which mpv can access it later on. But the downside to this method is that it will take too long for anime that have 100+ episodes.

**Additional context**

I think this project might help to do that, not so sure how much it will really help.
https://github.com/jaseg/python-mpv

I hope you do consider this request!!

**Comment by toomyzoom** [comment]
You better using _grab_ command.
- Start mpv with ipc --input-ipc-server switch
- Parse animdl grab json output to get the link
- Create loadfile command in as json payload {"command":["loadfile", <url>, <flags>, [<options>]]}. This is necessity because some link/site need http headers for referer to load the video which animdl provides.
- Pipe it to the ipc socket used when started mpv in 1st step (can use something like netcat, socat, or telnet)

This is related to my #169. The _stream_ command cannot use  script-opts which I used to control refresh rate. It's better if you start your own instance with custom config and pipe the links in using loadfile.

**Comment by justfoolingaround** [comment]
Using mpv's IPC-socket from the project has been deemed unfeasible for the project. It would require an entire IPC client and custom player setups. You can always use `grab` and create a wrapper until a feasible way is obtained.
