### ISSUE TITLE
Download Folder

### ISSUE THREAD

**Issue by haj1s** [justfoolingaround/animdl#21]
Hey it's me again,
I was recently trying to download the anime "KUMO DESU GA, NANI KA?" with animdl, and I encountered an issue because the anime name has a question mark and the thing is. windows doesn't allow folder names with a question mark, a possible solution that I thought of was an option to rename the folder yourself, I'm a little bit nerdy about this stuff but not too nerdy that I can solve it myself so I reached out :P

**Comment by justfoolingaround** [comment]
Fixed. It was kinda due to a whitespace character in the end of the folder name. The problem regarding Windows not allowing certain characters was always considered and there was a internal fix applied to this.

Those characters are replaced by ` - `, with the whitespaces. These characters appearing at the end is a rare case and hence, during the replacement, a whitespace was added which wasn't accounted for by `pathlib`.

Thanks for reporting this issue!

**Comment by haj1s** [comment]
oh okay, great work!
