### ISSUE TITLE
issue with launching app

### ISSUE THREAD

**Issue by thaynos** [justfoolingaround/animdl#3]
![image](https://user-images.githubusercontent.com/83282129/119455546-bf523f00-bd4a-11eb-924a-c14b08224fe8.png)

**Comment by thaynos** [comment]
i installed the req.txt and did whatever u said
but then this issue came
![image](https://user-images.githubusercontent.com/83282129/119461717-06433300-bd51-11eb-9b68-9a87824044db.png)
also i do have mpv but it doesnt seem to detect

**Comment by justfoolingaround** [comment]
Aight, the NoneType headers should be gone now. About mpv, is it installed on PATH? The best way to test this is to simply type in "mpv" in the terminal window (in this case, cmd) because the detection algorithm literally does the same.

If it's installed in the PATH properly it'll show: 
![image](https://user-images.githubusercontent.com/79979949/119463007-0b0fe300-bd61-11eb-9afc-07078a52b5af.png)

Let me know if you have trouble setting it up in the PATH.

**Comment by justfoolingaround** [comment]
Wait a minute, did you try to install mpv with.. pip?

Aight, that's not how you're supposed to do it. `mpv` is a completely external dependency (it is not a Python module that you install with pip.)

I'll guide you through the installation of `mpv`:

Head to [the download page of mpv](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20210523-git-6c1dd02.7z/download) (this one is the latest Windows binary from the official site) and download the associated file. 

Then after, just extract the contents to a folder. Let's make it in `C:\mpv\`, in a folder named `mpv` in your C: drive. Now, the main part, adding mpv to your PATH. 

For that, simply follow the steps in these [instructions](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/). Just remember that the last thing you're going to add to the PATH is `C:\mpv`. If you're having problems with these instructions, let me know. If you solve this by yourself, just close the issue as all the problems should be fixed.

**Comment by thaynos** [comment]
uh i used pip cuz i dont have admin privs and adding to path requires admin :(

**Comment by justfoolingaround** [comment]
Oh boy, this will be painful to even perform.

Firstly, I want you to do a `git pull` or a redownload (because I just fixed the headers popping issue).

And, the workaround for the PATH installation is going to be a bit painful (not to do, but for me as a developer to suggest this). Do this if you want to be able to stream without any sort of Administrator privilege. Make sure you add `mpv` to PATH after you get that privilege.

Extract the contents of that download (the `mpv` download from the link I gave you above) straight to the `animdl` working directory (the folder you've downloaded animdl to).

The streaming should be enabled that way. 

If you don't want to do this dirty trick, I can suggest just downloading the episodes and watching it that way using something other than `mpv`, you can delete downloads after watching.

**Comment by thaynos** [comment]
how is it a dirty trick? ive used something like this for aria2c by putting its exe file int the directory.

**Comment by justfoolingaround** [comment]
Usually not installing external dependencies the proper way and just adding them to the working directory is considered dirty.

If you can simply add it to a commonly accessible directory, such as PATH, it will perform perfectly for every application that requires it. This prevents a lot of copy pasting same files to the directory and if you intend to contribute to the projects that you run, you need to manually exclude the dependencies out of there.

In any case, is the issue fixed?

**Comment by thaynos** [comment]
ah ok alr idr have any need for mpv so i wont be downloading it yet
also it dint work yet
![image](https://user-images.githubusercontent.com/83282129/119473914-b0748800-bd5c-11eb-835a-6281391dd252.png)

**Comment by thaynos** [comment]
tysm for your quick replies i appreciate it a lot

**Comment by thaynos** [comment]
also i noticed is 500mb is there any way to real time compress or download a smaller version 
i prefer 720p and <200mb file size
id rather download from nyaa if the size is so big

**Comment by thaynos** [comment]
my pc is really slow and it takes 30mins to reencode and compress videos on handbrake

**Comment by justfoolingaround** [comment]
> ah ok alr idr have any need for mpv so i wont be downloading it yet
> also it dint work yet

That should now be fixed (well, it wasn't an issue, animdl required 3.9+, but since it's just a single line of code that decreases the support, I extended the support to 3.6+ by modifying the mechanism).

> also i noticed is 500mb is there any way to real time compress or download a smaller version
> i prefer 720p and <200mb file size
> id rather download from nyaa if the size is so big

I'd suggest ffmpeg for incredibly fast downscaling / quality comparison. There's absolutely no way of selecting a preferred quality during downloads internally. If you're worrying about download speeds, keep in mind that the provider that the search query uses gives out Google API Storage URLs which download at the maximum speed possible. 

It shouldn't take any time to re-encode and/or compress the videos because the site probably does so forehand.

A possible way to resolve this should be to search your anime in the supported sites: 4Anime, 9Anime, AnimeFreak or Twist and just copy the URL to the query.

I can't assure you that you'll get anime of lesser quality, but it's worth a shot. 

Kinda funny that the fact that `animdl` provides the highest quality is a problem in this use case lol.

**Comment by thaynos** [comment]
some other scripts have a quality choser thats why i asked. idrc much about download speeds as long its above 500kbps. wdym it doesnt take time to re-encode?

**Comment by justfoolingaround** [comment]
Since most providers available in animdl are site-based, the anime is sourced from their content delivery networks (CDNs), the anime is already downscaled and/or re-encoded to oblivion (since that'll allow them to store more anime). Hence, it should take comparatively lesser time.

The one of the provider here that doesn't re-encode their anime and provides it at the highest quality as is, is Twist.

**Comment by thaynos** [comment]
handbrake is basically ffmpeg gui i think

**Comment by thaynos** [comment]
> Since most providers available in animdl are site-based, the anime is sourced from their content delivery networks (CDNs), the anime is already downscaled and/or re-encoded to oblivion (since that'll allow them to store more anime). Hence, it should take comparatively lesser time.
> 
> The one of the provider here that doesn't re-encode their anime and provides it at the highest quality as is, is Twist.

idts its as compressed as animepahe tho 
also what about a download quality changer

**Comment by justfoolingaround** [comment]
> handbrake is basically ffmpeg gui i think

Huh, then the encoding time should be closer to what ffmpeg has to offer.
 
> idts its as compressed as animepahe tho
> also what about a download quality changer

A download quality changer is impossible as the mp4 sources are a single yield, having a post processor to do so would take the same time as the re-encoder. Moreover, ffmpeg would be a required dependency which is not-so-light-weight and would effectively remove the light-weightness of `animdl`. I'm sorry about that. 

In an m3u8 yield scenario, multiple qualities are possible. However, HLS downloading is still-in-progress feature as making a fast and efficient HLS downloader is difficult.

**Comment by justfoolingaround** [comment]
In any case, seems like the issue with launching AnimDL has been solved. Thanks for reporting that to me! If there's anything else, we can always re-open the issue.

**Comment by thaynos** [comment]
dont some sites allow multiple quality downloads?
some other scripts allow you to choose thats why i asked

**Comment by justfoolingaround** [comment]
AnimePahe, 9Anime and more allows multiple quality "streaming" but not downloading. Other scripts you mentioned probably use HLS downloading which is bad because HLS streams exist to combat downloading itself and are preferred for streaming. If you're desperate for this, I'll add a "grab" option that'll give you the m3u8 streams associated.

Then after, you can use ffmpeg to "download" and convert the streams to the extension of your choice.
