### ISSUE TITLE
add all download links on idm at once

### ISSUE THREAD

**Issue by shahrier-nafis** [justfoolingaround/animdl#34]
#28 
then add a feature to add all download to idm queue if possible, pls.

**Comment by justfoolingaround** [comment]
Problem is, it won't be sent to "IDM Queue" but rather would download all the files simultaneously hence, this can't be implemented. I'm sorry lol.

**Comment by Justaus3r** [comment]
@justfoolingaround 
Sorry for the intrusion(lol just killin time as i have exam for chemistry course nd its frustrating xdd)

Just a thought,maybe a function can be created having all the download links(in a list),it would check if the current download is complete and if it is,then download the next episode.i don't know if its possible to check if the download is complete in idm but if is then the feature requested by the op can be implemented.

**Comment by justfoolingaround** [comment]
_Dude you underestimate me a lot._

There's no way to check the completion for the current download other than checking if the "requested" file for downloading is in the PATH.

Loading all the downloads to IDM at once would download all the files together. It won't wait for any downloads to complete.

**Comment by justfoolingaround** [comment]
If you mean a sequential adding... the code in animdl already does so. @Justaus3r

**Comment by Justaus3r** [comment]
@justfoolingaround 
>>_Dude you underestimate me a lot._

I think there is a misconception here,i don't underestimate you in the least.actually quite the opposite.you know more python than i do and i am relatively new to python(only been 2 -3 months since i started programming in python).i was only giving a suggestion ,i was not tryna be flexy or anything.**BUT** if it turned out like that to ya,i apologize 😅.i know it kinda seems like someone is underestimating you or flexing when they keep commenting on your every issue or keeps pointing things out in your code BUT my intention wasn't to underestimate u or anything so chill out man!.
 
>>Loading all the downloads to IDM at once would download all the files together. It won't wait for any downloads to complete.If you mean a sequential adding... the code in animdl already does so.

naruhodo ,yeah i meant sequential adding,(sorry english ain't my native language)

regards,

**Comment by justfoolingaround** [comment]
Oh nah, I meant that line sarcastically.

I was just implying something like "I've already tried that" xd.

**Comment by Justaus3r** [comment]
>>Oh nah, I meant that line sarcastically.
I was just implying something like "I've already tried that" xd.

Ah good,btw that sarcasm tho 😅,xdd

**Comment by Justaus3r** [comment]
```/s - starts queue in scheduler```

Source:-https://www.internetdownloadmanager.com/support/command_line.html

Doesn't this work?
