### ISSUE TITLE
Episode download failures from 9Anime & GogoAnime sources

### ISSUE THREAD

**Issue by Navid906** [justfoolingaround/animdl#4]
Can I specify any quality in it and when downloading from gogoanime & 9anime there were some episodes didn't download. What's the problem??

**Comment by justfoolingaround** [comment]
As of now, you cannot really select a specific quality for download. Taking examples of 9Anime and GogoAnime, downloads are done from the sources directly provided by them

Can you let me know about what the failed anime were along with their associated episode numbers?

Sometimes GogoAnime and 9Anime doesn't provide a MP4 quality, they may provide m3u8 which is not supported. If you can't let me know about the anime, you can simply run:

```py
animdl.py grab -q "<your anime url or query here>" -s "<episode associated>"
```

That'll show you all the available urls from source. If the urls do not contain a MP4, that is the problem. HLS Downloading is a work-in-progress feature and as mentioned in [this section](https://github.com/justfoolingaround/animdl#supported-sites), the streams aren't downloadable if the urls are m3u8.

9Anime is notorious with its stream urls, sometimes it contains a MP4 and sometimes it doesn't. There isn't a way to solve this problem as the source itself is problematic.

GogoAnime provides long lasting streams, that is, if it doesn't contain an MP4, it'll probably not work in a re-run.

**Comment by justfoolingaround** [comment]
Update on this: 9Anime is fully fixed with powerful internal scrapers that scrape through MP4Upload, StreamTape, VidStream and MyCloud.

**Comment by justfoolingaround** [comment]
Second update: Quality selection is added as a limited feature. 

A `QUALITY` variable is added at the [configurations](https://github.com/justfoolingaround/animdl/blob/master/core/config/__init__.py) which will allow you to select the preferred quality.

Keep in mind this works alongside HLS downloading and hence, only AnimePahe supports this feature. Since, download errors in HLS use case and quality selection are now added. I'll close this issue for now, if it persists, feel free to re-open this.
