### ISSUE TITLE
Most of the Anime is not working

### ISSUE THREAD

**Issue by animeshxd** [justfoolingaround/animdl#5]
raise Exception('Could not find session key from VidStream; associated url: "%s" (Include this in your GitHub issue!).' % vidstream_embed_url)
Exception: Could not find session key from VidStream; associated url: "https://vidstream.pro/e/LNPEREQEOJXW" (Include this in your GitHub issue!)

**Comment by justfoolingaround** [comment]
Oh boy, the purpose of that exception raise was to get issues over new VidStream DRMs (if they ever make one). Aight, so, solving this one:
Seems like the `skey` was there but due to some issues with VidStream's servers, it didn't get a valid page:

![image](https://user-images.githubusercontent.com/79979949/120577639-518dcd80-c444-11eb-8a85-afcfe498ce23.png)

Hold on, I'll add an immediate "retry" function in the internal VidStream handlers. Also, did you retry downloading/streaming that anime?

**Comment by justfoolingaround** [comment]
Oops, seems like it auto closed after that commit. Anyway, it seems to be yielding seamlessly now.

![image](https://user-images.githubusercontent.com/79979949/120578903-49369200-c446-11eb-8d93-79812f3592ce.png)
