### ISSUE TITLE
[Feature Request] IDM Support

### ISSUE THREAD

**Issue by as280093** [justfoolingaround/animdl#6]
currently, Download does normal download but I like to use IDM 
and I found out this link 
https://stackoverflow.com/questions/22587681/use-idminternet-download-manager-api-with-python

**Comment by justfoolingaround** [comment]
I'm aware about IDM integration calls with Python, as a matter of fact, the foundational code for that exact purpose is already [in the codebase](https://github.com/justfoolingaround/animdl/blob/master/core/downloader/idmanlib.py).

**Why this feature was considered unusable?**

There's actually no way to know a download's completion when calling IDM through Python. Due to this, IDM will be called immediately once a stream url is fetched. This by itself is not a problem. The problem is how IDM uses these links. Your downloads won't be added to a queue whatsoever. All the called IDM instances will begin downloading concurrently.

This is a massive performance side issue when bulk downloading anime like One Piece; all 900~ episodes will download at once. Needless to say, the internet will suffer and the device itself would be completely unusable due to the performance drain caused due to such un-curated I/O actions. 

If you still want it, I can add it.

**Comment by justfoolingaround** [comment]
Aight, I found a way to track the download completion and IDM is now supported.

Just use the `--idm` flag with the current `download` command for making automatic calls to IDM. A keyboard interrupt / CTRL+C in the active IDM process wait will ignore the wait and continue making calls for other episodes in the queue!
