### ISSUE TITLE
Support for Donghua website: animexin.xyz

### ISSUE THREAD

**Issue by Anu-bhav** [justfoolingaround/animdl#81]
If possible kindly extend support for donghua website like `animexin.xyz`.

It looks like there is no cloudfare protection and I do not think it has some antibot protection as well.

**Comment by justfoolingaround** [comment]
Added, however, the embed url for animexin.xyz `gdriveplayer.to` did not make into the project due to the anti-bot protections surrounding that embed.

That embed is scrapable however it would take a lot of time and effort. At the time, I can't give it a go.

DailyMotion extractor has been added and works perfectly with the site!

If someone wants to work with `gdriveplayer.to`, here's a url for that embed:
```
https://gdriveplayer.to/embed2.php?link=HRQ0gEFQyRwozzmqWmi5Lwv%252BrjcL7wcU73GAXtjz%252BHbSMQZRhA6kNKGbv3rOfBAnMApAo610xbrVXiDDPkopPNBIlPXM3wKPjqJCZFap8wiM%252B1%252FS8rTOEzSLDv2pP4jmMBMzVZrDAlQd0fk4SIowCXZSl%252FFmbZTyO%252B%252FgedsTnFMvARek2ptTldDtHHKEgXneZmRL44RTcbXG25co%252Fo8XB%252FJ4rtOhRRr1JmM3IRjcPhx%252B2yTXaAc4uNcK00GHtFu%252B%252B39CDIvUITnQ%252FH7QHJsl1fx61F13CbYBo5ILebgDJMb3C5i60vyxBCLeWhwH8fpgGwxvEfjzKfX%252BFN4UqF7FYiLrEMEkELNeumxfj3jOwxCuPLSi9kSUrb9PE4R%252By%252FQF6k0YKdnlA8uljLUujl4hFw
```

_Good luck to them!_

Thank you for suggesting this site, animdl now supports it. (Not the searcher yet but it will be added soon™️)

**Comment by Anu-bhav** [comment]
Thank you so much <3
