### ISSUE TITLE
Feature Request: Use standard and parse-able anime title in mpv title.

### ISSUE THREAD

**Issue by aizuchan** [justfoolingaround/animdl#86]
I currently using [Taiga](https://github.com/erengy/taiga) to manage my library but animdl doesn't give mpv anime title to its name when streaming. 

I wonder if you can pass the title name to mpv in a way that Taiga or other similar applications will be able to detect and do its job (in which to synchronize my progress)

**Comment by justfoolingaround** [comment]
Aight wait, this is a tricky one! Since animdl does not even try to find out what you're watching if you use a direct url, it has essentially no way to find the name.

This will take time as **every** provider will now require a new function and the project just has a lot of providers.

Please bear with me.

The new titles will look like:

`[%providername%] %anime% - %episode%`

For example:

`[tenshimoe] One Piece - 1`

Taiga should be able to parse this as the library it uses successfully parses this.

**Comment by justfoolingaround** [comment]
Done, now your titles will be parse-able by Taiga and/or Trackma!

**Comment by aizuchan** [comment]
I have noticed this since 2 days ago but didn’t come here to report. 
Thank you, and GJ 👍
