### ISSUE TITLE
Improvement - Add version to readme.md

### ISSUE THREAD

**Issue by Anu-bhav** [justfoolingaround/animdl#87]
Hi @justfoolingaround,

For now, we only know the version that is on the release page unless we keep updating the app randomly after a lot of commits, there is no actual way of knowing the current version.

If possible, do add the version of the app on the readme.md itself perhaps under the logo. 
And for every version increment, do change it accordingly.

And I'd like to add that the new logo design is 🔥.

**Comment by justfoolingaround** [comment]
You have now single handedly made me add a patch version change to **every** commit now.

This means that the project will just prompt you to upgrade very very often.

There is no real need to do anything regarding adding the version to the readme as the version will just update.

Thanks for the remarks on the new logo! <code><img src="https://cdn.discordapp.com/emojis/852592161405141012.png" height=18px></code>

**Technical changes surrounding the version update:**

- This change was made possible due to git's pre-push hook. On each push a script will run, update the version and sneak in a commit in it.
