### ISSUE TITLE
How to make animdl download using IDM?

### ISSUE THREAD

**Issue by vannessqn** [justfoolingaround/animdl#92]
Sorry I dont know you said in the features can be download with IDM but I dont see any tutorial, the HLS thingy showed like 400-500 kbps while when I manual download from animepahe with IDM showing 3-4 Mb/s

**Comment by justfoolingaround** [comment]
What you're downloading from AnimePahe from the browser are MP4s. These MP4s are protected by kwik using Cloudflare. 

animdl, hence, resorts to m3u8s. IDM cannot unfortunately download m3u8 or, HLS streams. animdl solves this issue by using its internal HLS downloader. The internal HLS downloader is equally as efficient as any downloader

The m3u8s are aimed at streaming more than downloading, so that might be the cause of the slower download speeds of such streams.

**Comment by vannessqn** [comment]
well unfortunately then, I like using animepahe because they encode the anime smaller but the quality still good, do you happen to know another site that has balance quality-size like it? 9anime is really good but the size is big if you wanna download 20-30 eps per use

**Comment by justfoolingaround** [comment]
I mean, in terms of size-ratio, GogoAnime is next in line.
